import type { ThemeRegistration } from "shiki";

const c = {
  void: "#0d0b14",
  abyss: "#12101c",
  dusk: "#1a1728",
  twilight: "#231f35",
  horizon: "#2e2a45",
  starlight: "#eddeff",
  veil: "#a89cc8",
  mist: "#7a7096",
  shadow: "#4e4468",
  violet: "#b59eff",
  duskRose: "#c084fc",
  nebula: "#d97fff",
  rosa: "#f06cb8",
  duskPink: "#e86fa8",
  polar: "#7ec8f4",
  glacier: "#5ab4e8",
  aurora: "#72f0c8",
  boreal: "#4dd9b0",
  tundra: "#38c4a8",
  halo: "#f0e6c0",
  moonlight: "#e8d5a3",
  duskGold: "#d4bc82",
} as const;

export const roraShikiTheme: ThemeRegistration = {
  name: "rora",
  type: "dark",
  colors: {
    "editor.background": c.abyss,
    "editor.foreground": c.starlight,
    "editor.selectionBackground": c.twilight,
    "editor.lineHighlightBackground": c.horizon,
    "editorLineNumber.foreground": c.shadow,
    "editorLineNumber.activeForeground": c.veil,
    "editorCursor.foreground": c.rosa,
  },
  tokenColors: [
    { scope: ["comment", "punctuation.definition.comment"], settings: { foreground: c.mist, fontStyle: "italic" } },
    { scope: ["string", "string.quoted", "string.template"], settings: { foreground: c.rosa } },
    { scope: ["constant.character.escape", "string.regexp"], settings: { foreground: c.duskPink } },
    { scope: ["constant.numeric", "constant.language", "constant.other"], settings: { foreground: c.nebula } },
    { scope: ["keyword", "storage.type", "storage.modifier", "keyword.control"], settings: { foreground: c.violet } },
    { scope: ["keyword.operator", "punctuation.separator", "punctuation.terminator", "punctuation"], settings: { foreground: c.duskRose } },
    { scope: ["entity.name.function", "support.function", "meta.function-call.python", "meta.function-call entity.name.function"], settings: { foreground: c.aurora } },
    { scope: ["entity.name.type", "entity.name.class", "support.class", "support.type"], settings: { foreground: c.polar } },
    { scope: ["entity.name.tag", "support.type.property-name"], settings: { foreground: c.polar } },
    { scope: ["variable", "variable.other", "meta.definition.variable"], settings: { foreground: c.starlight } },
    { scope: ["variable.parameter"], settings: { foreground: c.veil, fontStyle: "italic" } },
    { scope: ["variable.language", "variable.language.this", "variable.language.self"], settings: { foreground: c.tundra, fontStyle: "italic" } },
    { scope: ["meta.decorator", "entity.name.function.decorator", "punctuation.decorator"], settings: { foreground: c.tundra } },
    { scope: ["entity.other.attribute-name", "entity.other.inherited-class"], settings: { foreground: c.polar, fontStyle: "italic" } },
    { scope: ["markup.heading", "entity.name.section"], settings: { foreground: c.halo, fontStyle: "bold" } },
    { scope: ["markup.bold"], settings: { foreground: c.starlight, fontStyle: "bold" } },
    { scope: ["markup.italic"], settings: { foreground: c.starlight, fontStyle: "italic" } },
    { scope: ["markup.underline.link", "string.other.link"], settings: { foreground: c.glacier } },
    { scope: ["markup.inserted", "diff.added"], settings: { foreground: c.boreal } },
    { scope: ["markup.deleted", "diff.removed"], settings: { foreground: c.duskPink } },
    { scope: ["markup.changed", "diff.changed"], settings: { foreground: c.duskGold } },
    { scope: ["invalid", "invalid.illegal"], settings: { foreground: c.rosa, fontStyle: "italic" } },
    { scope: ["invalid.deprecated"], settings: { foreground: c.duskPink, fontStyle: "italic strikethrough" } },
    { scope: ["meta.tag", "punctuation.definition.tag"], settings: { foreground: c.duskRose } },
    { scope: ["meta.brace", "meta.bracket"], settings: { foreground: c.veil } },
    { scope: ["support.type.builtin", "support.constant"], settings: { foreground: c.nebula } },
  ],
};
